### ISSUE TITLE
TypeORM connection fails due to SyntaxError

### ISSUE THREAD

**Issue by Swiftb0y** [pezzetti/base-app-nestjs#1]
Currently, running the code outside of `ts-node` results in a `SyntaxError: Cannot use import statement outside a module` because the `ormconfig.js` is pointing at the `src` dir when specifying the typeorm entities (`"entities": ["src/**/**/**.entity{.ts,.js}"],`). This only works from within `ts-node`. There are two solutions to the problem: 

## Solution 1

just replace the `src` with `dist`. Pro: Simple, minimal change required; Con: requires rebuild when entities are changed.

## Solution 2

Convert ormconfig.json to typescript module and construct path conditionally.
detection via TypeStrong/ts-node#846. Pro: more solid approach, doesnt suffer from the Con from solution 1; Con: more complicated, requires bleeding edge version of ts-node, ts-node specific solution.

**Comment by pezzetti** [comment]
Hi @Swiftb0y  thanks for contributing.
I could use some help to fix this issue.
Could you submit a pull request?

Thanks in advance

**Comment by Swiftb0y** [comment]
Of course. What Solution do you prefer?

**Comment by pezzetti** [comment]
I believe that Solution 2 would be nice. What do you think?

**Comment by Swiftb0y** [comment]
I need to look into the details a bit more but I think it's possible without too much hassle.
